### ISSUE TITLE
Failed to load encryption key: signing key lacks private key

### ISSUE THREAD

**Issue by mharrend** [hoffie/lemoncrypt#1]
Dear @hoffie ,

thanks for making this code public.

I tried to use your program today but I am always getting the following error message:
failed to load encryption key: signing key lacks private key

This seems to be related that my private key is a GPG sub key and, thus, not found by your algorithm which searches for a Primarykey.
I also tried to generate differen PGP keys to get a primary encryption key but I always only get the signing key as a default primary key.

Can you please explain how I can obtain a working PGP key?

Thank you in advance

**Comment by hoffie** [comment]
Hi mharrend,

sorry for not replying earlier. I see that you already have done some debugging in your fork of the repo. Did you have success?
Unfortunately, I will only have time to have a deeper look at this at the weekend.

However, I still remember similar issues once I had upgraded my keyring from a previous format (gpg v1?) to a more recent one, so it may be related to that.

I will get back to you at the weekend, once I had a deeper look at the issue!

Kind regards,

Christian

**Comment by mharrend** [comment]
Hi Christian,

thank you very much for looking into it.
I am also quite busy this week, so most likely, I can also only
investigate further from Friday evening on. But I will also try to look
into it by myself.

Thank you very much,

Marco
-- 
Marco A. Harrendorf <marco.harrendorf@cern.ch>
KIT - IEKP

Am Dienstag, den 02.08.2016, 12:26 -0700 schrieb Christian Hoffmann:

**Comment by hoffie** [comment]
Finally I had some time to look into this. I have generated a fresh set of suitable keys (gpg 2.1.14 on Arch linux).
- One key as the encryption target: `gpg --gen-key` and export it `gpg --export ABCDEF > ABCDEF.gpg`
- One key for signing: `gpg --gen-key` and export it including the private key `gpg --export-secret-keys DEF > DEF.gpg`

Indeed, I was able to reproduce the issue you mentioned.

The current code only works properly if the same key pair is used for encryption and signing (which is the mode I have recently tried). However, the config suggests that usage of different keys should be possible and this may be important security-wise, depending on the trust model of the runtime environment.

I have committed an initial attempt at fixing this. However, it will need proper testing until I will merge it to master. Until now, I have only confirmed that key loading works properly. I have not been able to test a full encryption run yet.

**Comment by mharrend** [comment]
Dear Christian,

thank you very much, after fiddling with it a little bit, it is now
working for myself.
I was following your receipt and had to do some workarounds but finally
I was able to encrypt and sign the emails. I did the following:

1) I generated a RSA key pair via gpg --gen-key, choosing option 1.
I found out that it was important to set no password for the key
because otherwise I got the error "signing key is not decrypted"

2) I exported the secret key two times via
gpg --export-secret-keys KEYID > enckey.pgp
gpg --export-secret-keys KEYID > signingkey.pgp

3) Downloaded your issue1 branch

4) Adjusted the lemoncrypt config and started lemoncrypt.

BTW: I know also what the issue with my original key was:
My original default PGP key consists of more than one signature and was also extended more than one time.
According to some bug reports the go openpgp implementation cannot handle extended signatures properly until now.

Thank you very much for your help and let me know if I can do some further checks or tests to help you with the new release.Best regards,

Marco

Am Samstag, den 06.08.2016, 09:44 -0700 schrieb Christian Hoffmann:

**Comment by hoffie** [comment]
Hi Marco,

glad to hear it worked for you! It should also work with encrypted private keys (passphrase) and I have recently verified this. It should also work with different signing and encryption keys (when using the fix from the issue1 branch).

I will now merge the branch and consider the issue solved. Please let me know if you have any further questions or issues!

Kind regards,

Christian
